name: flutter_instagram
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  provider: ^6.1.2
  uuid: ^4.4.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  assets: 
    - images/instagram_logo.png
    - images/logo-text.png
    - images/person.png

  uses-material-design: true

