// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAu8kyJBRsg-gY0Dxze7DggiKJAtmk3g',
    appId: '1:985549854820:web:8cf6d7c640e2cb4ea8e771',
    messagingSenderId: '985549854820',
    projectId: 'flutter-insta-clone-c7e07',
    authDomain: 'flutter-insta-clone-c7e07.firebaseapp.com',
    storageBucket: 'flutter-insta-clone-c7e07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwfI41-3Zp81WhkSJrEmAOBoN2mwWqrI',
    appId: '1:985549854820:android:b23b08db9be198d0a8e771',
    messagingSenderId: '985549854820',
    projectId: 'flutter-insta-clone-c7e07',
    storageBucket: 'flutter-insta-clone-c7e07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmImL-Ac4HExxttWyFBTTTNngeZCxFWBQ',
    appId: '1:985549854820:ios:34654b7a7114a137a8e771',
    messagingSenderId: '985549854820',
    projectId: 'flutter-insta-clone-c7e07',
    storageBucket: 'flutter-insta-clone-c7e07.appspot.com',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmImL-Ac4HExxttWyFBTTTNngeZCxFWBQ',
    appId: '1:985549854820:ios:34654b7a7114a137a8e771',
    messagingSenderId: '985549854820',
    projectId: 'flutter-insta-clone-c7e07',
    storageBucket: 'flutter-insta-clone-c7e07.appspot.com',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPAu8kyJBRsg-gY0Dxze7DggiKJAtmk3g',
    appId: '1:985549854820:web:971cddc3afe8f242a8e771',
    messagingSenderId: '985549854820',
    projectId: 'flutter-insta-clone-c7e07',
    authDomain: 'flutter-insta-clone-c7e07.firebaseapp.com',
    storageBucket: 'flutter-insta-clone-c7e07.appspot.com',
  );
}
